### PR TITLE
Update index.vuln.js

### PR DESCRIPTION
**Pull request by bassmalla**

### CODE REVIEW

**Comment by bassmalla** [comment]
@shieldfy details SQl Injection

**Comment by bassmalla** [comment]
@shieldfy details /index.vuln.js

**Comment by bassmalla** [comment]
@shieldfy details /index.vuln.js

**Comment by bassmalla** [comment]
@shieldfy details /index.vuln.js

**Comment by bassmalla** [comment]
@shieldfy details SQL Injection

**Comment by bassmalla** [comment]
@shieldfy details SQl Injection

**Comment by bassmalla** [comment]
@shieldfy details SQL Injection

**Comment by bassmalla** [comment]
@shieldfy details  line: 27

**Comment by bassmalla** [comment]
@shieldfy details SQl Injection in /index.vuln.js

**Comment by bassmalla** [comment]
@shieldfy details SQl Injection in line: 27

**Comment by bassmalla** [comment]
@shieldfy details /index.vuln.js line: 27

**Comment by bassmalla** [comment]
@shieldfy details line: 27 in /index.vuln.js

**Comment by bassmalla** [comment]
@shieldfy details 3 SQl Injection in /index.vuln.js line: 27, 23, 15

**Comment by bassmalla** [comment]
@shieldfy details SQL injection

**Comment by bassmalla** [comment]
@shieldfy details SQl injection

**Comment by bassmalla** [comment]
@shieldfy details  SQl Injection

**Comment by bassmalla** [comment]
@shieldfy ignore line: 15

**Comment by bassmalla** [comment]
@shieldfy yes

**Comment by bassmalla** [comment]
@shieldfy ignore line: 23

**Comment by 7ameed** [comment]
@shieldfy ignore

**Pull request closed without merging**
